Simplify and fix the 'flash' scripts
 - Instead of having multiple if/elif/fi blocks that all run nearly the
   same thing, use variables
 - Use consistent indent/formatting
 - Use the correct program name in the "Usage:" text
 - Fix a couple if blocks that were missing 'fi'
 - Fix a couple of invalid variable assignments ("$var = value" should be
   "var=value")

I haven't actually tested these, but then with the last 2 items, they
weren't working anyway.

diff --git a/lenovobios_firstflash b/lenovobios_firstflash
--- a/lenovobios_firstflash
+++ b/lenovobios_firstflash
@@ -18,109 +18,53 @@
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 
-## Don't add here. errors are expected.
-# set -u -e -v
-set -v
+set -u -e
 
-if [ $(uname -i) = "i686" ] || [ $(uname -m) = "i686" ]
-	then
-		echo "Running on i686. ok."
-		sleep 5
-elif [ $(uname -i) = "x86_64" ] || [ $(uname -m) = "x86_64" ]
-	then
-		echo "Running on x86_64. ok."
-		sleep 5
+# These are the tested platforms
+if [ $(uname -i) = "i686" ] || [ $(uname -m) = "i686" ]; then
+	echo "Running on i686. ok."
+	arch=i686
+	sleep 5
+elif [ $(uname -i) = "x86_64" ] || [ $(uname -m) = "x86_64" ]; then
+	echo "Running on x86_64. ok."
+	arch=x86_64
+	sleep 5
 else
 	echo "This script must be run on an i686 or x86_64 host. x86_64 is recommended."
 	exit 1
+fi
+if [ -f "DEBLOB" ]; then
+	# In a src archive or git
+	arch=.
 fi
 
 if [[ $EUID -ne 0 ]]; then
-   echo "This script must be run as root" 
-   exit 1
-fi
-
-if [ $(uname -i) = "i686" ] || [ $(uname -m) = "i686" ]
-	then
-		echo "Running on i686. ok."
-		sleep 5
-elif [ $(uname -i) = "x86_64" ] || [ $(uname -m) = "x86_64" ]
-	then
-		echo "Running on x86_64"
-		sleep 5
-else
-	echo "This script must be run on an i686 or x86_64 host. x86_64 is recommended."
+	echo "This script must be run as root"
 	exit 1
 fi
 
-# USE ROOT OR SUDO WHEN EXECUTING THIS
-
-# for T60 or X60 owners with Lenovo BIOS
-# does the 1st part of the flash before shut down
-
 if (( $# != 1 )); then
-	echo "Usage: ./lenovobios_firstflash yourrom.rom"
-	echo "usage: ./lenovobios_firstflash path/to/yourrom.rom"
+	echo "usage: $0 path/to/yourrom.rom"
 	echo "You need to specify exactly 1 file"
 	exit 1
 fi
-if [ ! -f $1 ]; then
+if [ ! -f "$1" ]; then
 	echo "File not found!"
 	exit 1
 fi
 
-$errOut = " \
-			BUCTS failed. Make sure BUC.TS is 1, or else you will brick your machine. \
-			ABORTING so as to protect against bricking the machine. \
-			"
-if [ ! -f "DEBLOB" ]
-	then
-		# this means we are working in bin
-		if [ $(uname -i) = "i686" ] || [ $(uname -m) = "i686" ]
-			then
-				# i686
-				# needed for first flashing, otherwise machine will be bricked
-				{ # try
-					./bucts/i686/bucts 1
-				} || { # catch
-					echo "$errOut"
-					exit 1
-				}
-		else
-			# x86_64
-			# needed for first flashing, otherwise machine will be bricked
-			{ # try
-				./bucts/x86_64/bucts 1
-			} || { # catch
-				echo "$errOut"
-				exit 1
-			}
-else
-	# this means we are working in src
-	# needed for first flashing, otherwise machine will be bricked
-	{ # try
-		./bucts/bucts 1
-	} || { # catch
-		echo "$errOut"
-		exit 1
-	}
-fi
+errOut="
+	BUCTS failed. Make sure BUC.TS is 1, or else you will brick your machine.
+	ABORTING so as to protect against bricking the machine.
+"
 
-# run both. one will fail (and be harmless), the other will succeed. 
+set -v
+# for T60 or X60 owners with Lenovo BIOS
+# does the 1st part of the flash before shut down
 
-if [ -f "DEBLOB" ]; then
-	# Means we are in src archive or git
-	./flashrom/flashrom_lenovobios_sst -p internal -w $1
-	./flashrom/flashrom_lenovobios_macronix -p internal -w $1
-elif [ $(uname -i) = "i686" ] || [ $(uname -m) = "i686" ]
-	then
-		# Means we are in bin archive and on an i686 host
-		./flashrom/i686/flashrom_lenovobios_sst -p internal -w $1
-		./flashrom/i686/flashrom_lenovobios_macronix -p internal -w $1
-elif [ $(uname -i) = "x86_64" ] || [ $(uname -m) = "x86_64" ]
-	then
-		# Means we are in bin archive and on an x86_64 host
-		./flashrom/x86_64/flashrom_lenovobios_sst -p internal -w $1
-		./flashrom/x86_64/flashrom_lenovobios_macronix -p internal -w $1
-fi
+# needed for first flashing, otherwise machine will be bricked
+./bucts/$arch/bucts 1 || { printf '%s' "$errOut"; exit 1; }
 
+# run both. one will fail (and be harmless), the other will succeed.
+./flashrom/$arch/flashrom_lenovobios_sst      -p internal -w "$1" || true
+./flashrom/$arch/flashrom_lenovobios_macronix -p internal -w "$1" || true
